### PR TITLE
[REVIEW] Fix resize function based on aspect ratio of the video and window size

### PR DESCRIPTION
**Pull request by pablodiegoss**
Issue #8

### CODE REVIEW

**Comment by pablodiegoss** [comment]
I still need to fix the initial resize when you first open the example and test on mobile devices, but it is already working better.

**Comment by rodrigocam** [comment]
Thank you for your PR!
With the body without style="overflow: hidden; position: fixed" the scroll bars (horizontally and vertically) are 
showing in the page, how can we disable the scroll bars now?

**Comment by pablodiegoss** [comment]
I had quite some trouble in this issue, browsers don't work well with objects bigger than their screen, so we can't use an adjusted canvas to not distort the video image.
i ended up creating another canvas and cutting the image from the video adjusted for the user screen size to use in the new size of the screen canvas.
The rules for mobile devices on Portrait mode, landscape and on desktops all differ, so there are conditions for each on the ResizeWindow method.

**Comment by rodrigocam** [comment]
Thank you, it seems good the resize and device rotation!

**Pull request merged**
